swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: mock-controller
    description: Mock Controller
paths:
  '/v2/courses/{courseSectionId}/learningAppToolAssignments/score':
    post:
      tags:
        - mock-controller
      summary: synchGrade
      operationId: publishEven1tUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X-Authorization
          in: header
          description: PI token
          required: true
          type: string
        - name: courseSectionId
          in: path
          description: courseSectionId
          required: true
          type: string
        - in: body
          name: payload
          description: payload
          required: true
          schema:
            $ref: '#/definitions/SubmitScoreDTO'
      responses:
        '201':
          description: OK
          schema:
            $ref: '#/definitions/HeadersBuilder«object»'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  HeadersBuilder«object»:
    type: object
    title: HeadersBuilder«object»
  SubmitScoreDTO:
    type: object
    properties:
      lappAssignmentId:
        type: string
      piId:
        type: string
      rawItemScore:
        type: number
        format: double
      submissionTime:
        type: string
    title: SubmitScoreDTO